### ISSUE TITLE
0.3.2: missing version git tags

### ISSUE THREAD

**Issue by kloczek** [sphinx-contrib/zopeext#6]
According to https://pypi.org/project/sphinxcontrib-zopeext/ latest version is 0.3.2 however there there is no coresponding git version tag.
Is it possible to add at least last 0.3.2 version tag?

**Comment by mforbes** [comment]
Is the branch label [0.3.2](https://github.com/sphinx-contrib/zopeext/tree/0.3.2) not sufficient?

**Comment by kloczek** [comment]
Branches and tags are not the same things.
https://github.com/sphinx-contrib/zopeext/tags
If you know exact hash all what you need to do is `git tag 0.3.2 <hash>l;git push`.
Also tagging is sending email notyfication to all people whoo are watching your repo.

**Comment by mforbes** [comment]
[Figured it out](https://foss.heptapod.net/mercurial/hg-git/-/issues/193):

```
hg tag --git -r ...
```

**Comment by kloczek** [comment]
Thank you 👍

**Comment by kloczek** [comment]
Looks like now it is missing git tag for 0.3.3 😋

**Comment by mforbes** [comment]
Thanks.  I keep forgetting this.  Need to see if there is a default way to tag both git and hg commits!

**Comment by kloczek** [comment]
Thank you 😄 
I'm usimg tagged tar ball as input to build my rpm package as sdist has no included doc/ contesnt.

**Comment by mforbes** [comment]
Hopefully I will remember next time, but feel free to ping me if I forget.
