### ISSUE TITLE
Newer importlib-metadata

### ISSUE THREAD

**Issue by frenzymadness** [sphinx-contrib/zopeext#9]
I see `importlib-metadata = "^4.8.1"` in the project dependencies but AFAIK this project works fine also with versions 5 and 6.

**Comment by mforbes** [comment]
Probably, but this is only a dev. dependency, and only used for `python < 3.8`.  I am curious how this causes an issue?  *(I wish there were a way of dynamically updating version dependencies while running all tests to automatically bump dependencies... do you know any useful tools?)*

**Comment by frenzymadness** [comment]
In Fedora Linux, we have this package as an RPM package and its runtime dependencies are generated from its metadata after we build a wheel from the source. The problem is that the version of importlib-metadata is too new in Fedora for zopeext. That's something we can fix in our configuration but I just wanted to let you know that we are testing zopeext with newer importlib-metadata and it works fine.

What is Interesting is that if I build a wheel from the latest master branch, I see importlib-metadata in "Requies-Dist":
```
Metadata-Version: 2.1
Name: sphinxcontrib-zopeext
Version: 0.3.3
Summary: Provides sphinxcontrib.zopeext.autointerface for documenting Zope interfaces.
License: BSD-2-Clause
Author: Michael McNeil Forbes
Author-email: mforbes@alum.mit.edu
Requires-Python: >=3.6.2,<4
Classifier: License :: OSI Approved :: BSD License
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.7
Classifier: Programming Language :: Python :: 3.8
Classifier: Programming Language :: Python :: 3.9
Classifier: Programming Language :: Python :: 3.10
Classifier: Programming Language :: Python :: 3.11
Provides-Extra: docs
Requires-Dist: Sphinx (>=3.4.2,!=3.5.*,!=4.0.*,!=4.1.*,<6.0.0) ; python_version >= "3.10"
Requires-Dist: Sphinx (>=3.4.2,<6.0.0) ; python_version < "3.9"
Requires-Dist: importlib-metadata (>=4.8.1,<7.0)
Requires-Dist: sphinx-book-theme (>=0.1.7,<0.2.0) ; extra == "docs"
Requires-Dist: zope.interface (>=5.2.0,<6.0.0)
Project-URL: Bug Reports, https://github.com/sphinx-contrib/zopeext/issues
Project-URL: Documentation, https://zopeext.readthedocs.io/en/latest/
Project-URL: Source, https://github.com/sphinx-contrib/zopeext
Project-URL: Sphinx, https://www.sphinx-doc.org/
Project-URL: Sphinx Autodoc, https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html
Project-URL: Zope Interface, https://github.com/zopefoundation/zope.interface
Description-Content-Type: text/x-rst
```

**Comment by mforbes** [comment]
Thanks.  This is https://github.com/python-poetry/poetry/issues/2357: optional dependencies must apparently be included in an extra, so I will add a `test` extra.

**Comment by frenzymadness** [comment]
Interesting, thank you. Also, you've mentioned that importlib-metadata is needed only for `python < 3.8` so you can add this as an environment marker.
